"""
LearnOrbit PDF Export Service
Generates branded, styled PDF notes from markdown content.
"""

import os
import re
from datetime import datetime


def _md_to_text_blocks(md_text: str) -> list:
    """Parse markdown into a list of (type, content) tuples."""
    blocks = []
    lines = md_text.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("# "):
            blocks.append(("h1", line[2:].strip()))
        elif line.startswith("## "):
            blocks.append(("h2", line[3:].strip()))
        elif line.startswith("### "):
            blocks.append(("h3", line[4:].strip()))
        elif line.startswith("- [ ] ") or line.startswith("- [x] "):
            checked = line.startswith("- [x] ")
            blocks.append(("checkbox", (checked, line[6:].strip())))
        elif line.startswith("- ") or line.startswith("* "):
            blocks.append(("bullet", line[2:].strip()))
        elif line.strip() == "":
            blocks.append(("blank", ""))
        else:
            blocks.append(("para", line.strip()))
        i += 1
    return blocks


def export_notes_pdf(notes_md: str, topic: str, username: str, output_dir: str) -> str:
    """
    Export notes as a PDF file. Returns the file path.
    Uses fpdf2 (pip install fpdf2).
    Falls back to a simple text file if fpdf2 is not available.
    """
    os.makedirs(output_dir, exist_ok=True)
    safe_topic = re.sub(r"[^\w\s-]", "", topic).replace(" ", "_")[:40]
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"LearnOrbit_Notes_{safe_topic}_{timestamp}.pdf"
    filepath = os.path.join(output_dir, filename)

    try:
        from fpdf import FPDF, XPos, YPos

        class NotesPDF(FPDF):
            def __init__(self, topic, username):
                super().__init__()
                self.topic = topic
                self.username = username

            def header(self):
                # Brand bar
                self.set_fill_color(99, 102, 241)  # Indigo
                self.rect(0, 0, 210, 14, "F")
                self.set_text_color(255, 255, 255)
                self.set_font("Helvetica", "B", 11)
                self.set_xy(10, 3)
                self.cell(0, 8, "⚡ LearnOrbit — AI Learning Intelligence", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                self.set_text_color(0, 0, 0)
                self.ln(4)

            def footer(self):
                self.set_y(-15)
                # Watermark bar
                self.set_fill_color(238, 242, 255)
                self.rect(0, 282, 210, 15, "F")
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(99, 102, 241)
                self.set_xy(10, 284)
                self.cell(
                    0, 5,
                    f"Generated by LearnOrbit for {self.username} | {datetime.utcnow().strftime('%d %b %Y')} | learnorbit.app",
                    new_x=XPos.LMARGIN, new_y=YPos.NEXT,
                )
                self.set_text_color(180, 180, 220)
                self.set_font("Helvetica", "B", 28)
                self.set_xy(50, 265)
                self.set_text_color(220, 220, 240)
                # Diagonal watermark text
                with self.rotation(30, x=105, y=148):
                    self.set_font("Helvetica", "B", 48)
                    self.set_text_color(230, 232, 255)
                    self.set_xy(30, 130)
                    self.cell(0, 20, "LearnOrbit")

        pdf = NotesPDF(topic, username)
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=20)

        # Title block
        pdf.set_fill_color(238, 242, 255)
        pdf.rect(10, pdf.get_y(), 190, 22, "F")
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(79, 70, 229)
        pdf.set_xy(14, pdf.get_y() + 4)
        pdf.cell(0, 7, f"📚 {topic}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(120, 120, 160)
        pdf.cell(0, 6, f"Learner: {username}  |  {datetime.utcnow().strftime('%d %B %Y')}",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(6)
        pdf.set_text_color(0, 0, 0)

        blocks = _md_to_text_blocks(notes_md)
        for btype, content in blocks:
            if btype == "h1":
                pdf.ln(4)
                pdf.set_font("Helvetica", "B", 15)
                pdf.set_text_color(79, 70, 229)
                # Strip emoji for fpdf compatibility
                clean = content.encode("ascii", "ignore").decode()
                pdf.multi_cell(0, 8, clean, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_draw_color(99, 102, 241)
                pdf.set_line_width(0.5)
                pdf.line(10, pdf.get_y(), 200, pdf.get_y())
                pdf.ln(2)
                pdf.set_text_color(0, 0, 0)
            elif btype == "h2":
                pdf.ln(3)
                pdf.set_font("Helvetica", "B", 12)
                pdf.set_text_color(67, 56, 202)
                clean = content.encode("ascii", "ignore").decode()
                pdf.multi_cell(0, 7, f"  {clean}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_text_color(0, 0, 0)
            elif btype == "h3":
                pdf.ln(2)
                pdf.set_font("Helvetica", "BI", 11)
                pdf.set_text_color(99, 102, 241)
                clean = content.encode("ascii", "ignore").decode()
                pdf.multi_cell(0, 6, f"    {clean}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_text_color(0, 0, 0)
            elif btype == "bullet":
                pdf.set_font("Helvetica", "", 10)
                clean = content.encode("ascii", "ignore").decode()
                pdf.set_x(16)
                pdf.multi_cell(180, 5.5, f"\u2022  {clean}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            elif btype == "checkbox":
                checked, text = content
                mark = "[x]" if checked else "[ ]"
                pdf.set_font("Helvetica", "", 10)
                clean = text.encode("ascii", "ignore").decode()
                pdf.set_x(16)
                pdf.multi_cell(180, 5.5, f"{mark}  {clean}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            elif btype == "para":
                pdf.set_font("Helvetica", "", 10)
                clean = content.encode("ascii", "ignore").decode()
                if clean.strip():
                    pdf.multi_cell(0, 5.5, clean, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            elif btype == "blank":
                pdf.ln(3)

        pdf.output(filepath)
        return filepath

    except ImportError:
        # Fallback: write plain text
        txt_path = filepath.replace(".pdf", ".txt")
        with open(txt_path, "w", encoding="utf-8") as f:
            f.write(f"LearnOrbit Study Notes\n{'='*40}\n")
            f.write(f"Topic: {topic}\nLearner: {username}\n")
            f.write(f"Generated: {datetime.utcnow()}\n{'='*40}\n\n")
            f.write(notes_md)
        return txt_path
    except Exception as e:
        raise RuntimeError(f"PDF generation failed: {e}")
